### ISSUE TITLE
please enable the github wiki

### ISSUE THREAD

**Issue by dimyme** [rescatux/rescatux#108] opened 2020-04-18 01:59 UTC
to make amends for all the dead links in the Docs, please enable the github wiki like https://github.com/dimyme/rescuetux/wiki

makes for quick collaboration.

**Comment by adrian15** [comment] 2020-04-19 22:18
1) Current documentation status for Rescatux:

* [adrian15sgd Youtube channel](https://www.youtube.com/user/adrian15sgd)
* [Old obsolete Rescatux wiki page](http://wiki.rescatux.org/)
* [Super Grub Disk org howto pages](https://www.supergrubdisk.org/wizard/)
* [Embedded Rescapp documentation](https://github.com/rescatux/rescapp/blob/master/plugins/grubeasy/local_doc.html)

2) My plan on documentation is:

* Use rescatux.org site
* Build online documentation from Rescapp embedded documentation
* supergrubdisk.org documentation redirects to rescatux.org site documentation
* wiki.rescatux.org redirects to rescatux.org site documentation

So, so far, I was not interested in collaborative documentation (a la wiki) because nobody offered to write documentation.

I prefer to use documentation based on wordpress pages because then everything is connected to the other pages. Wiki as a doc seems like a desert island.

3) I will think on your offer and trying to reuse wiki.rescatux.org or not.

**Comment by adrian15** [comment] 2020-04-19 22:44
4. Commenting on your fork wiki notes

* https://github.com/dimyme/rescuetux/wiki
** webchat without registering: The chat page already has a link to a chat web interface where you do not need to register. And it's a chat. It is not a forum thread (as your external webpage seems to simulate (like that old lluna service)).
** Rescuetux : The correct name for the distro is Rescatux
** lacks basic, crucial and critical functionality every step of the way: You can write it down as much as you want to. If you want anything of it to be fixed please open new issues detailing what you mean with every one of them
** super grub2 disk ISO downloads : Not sure why we need a link to SG2D here but, yeah, I also develop it.
** https://sourceforge.net/p/rescapp-arch-linux/wiki/Home/ : I encourage you to give this link a description so that people know what's about
** wiki SF : Idem. This should make clear that it's the rescapp-arch project and not the official one.
** SF mailing list : Ok

* https://github.com/dimyme/rescuetux/wiki/always-rescatux-breakage
** wont fix: I told you that some improvement could be made in the newest radeon videocards. But needs testing. I pointed you to https://github.com/rescatux/rescatux/issues/105 in the irc.
** Many Rescatux options break if you manually mount the partition you want to fix / rescue.: Open a new issue so that we can discuss there

* https://github.com/dimyme/rescuetux/wiki/rescapp
** Nothing to comment

* https://github.com/dimyme/rescuetux/wiki/to-do
** You can create new issues for each of these problems. And hopefully pull requests too

5. If you are going to create new issues please use this template:

### Issue
### Expected Behavior
### Actual Behavior
### Possible Fix
### Steps to Reproduce
1.
2.
3.
4.
### Context
* Your Environment
* Rescatux version used: 
* Computer videocard
* Computer cpu
* Other computer details

**Closed** 2024-05-12 15:07 UTC
